version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432" # Exposing PostgreSQL default port
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspace
    command: sleep infinity
    depends_on:
      - postgres

volumes:
  postgres_data:
