version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-ts
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: