version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo-list
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - mynetwork

  backend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - .:/workspaces/todo-list/backend
    command: sleep infinity
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  postgres:

networks:
  mynetwork:
